### ISSUE TITLE
go-file need endpoint:File.ReadAt

### ISSUE THREAD

**Issue by qudenger** [micro/go-file#1]
go-file has no endpoint:file.ReadAt, the file service client call the Reacat(), you will get the same []byte, maybe do these to fix it:
**define protof:**
    	rpc ReadAt(ReadRequest) returns(ReadResponse) {};
**fix client.go:**
    rsp, err := c.c.ReadAt(context.TODO(), &proto.ReadRequest{Id: sessionId, Size: size, Offset: offset})

**Comment by asim** [comment]
Replaced Read with ReadAt considering they both do the same thing https://github.com/micro/go-file/commit/0b597211b1720f04ef8f41817b955735b6b7513d
